import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import useSWR from 'swr'
import moment from 'moment-timezone'
import React from 'react';

const fetcher = (...args) => fetch(...args).then((res) => res.json())

function Games() {
 
  const { data: games, error, isLoading } = useSWR('http://127.0.0.1:5000/getData', fetcher)

  if (error) return <div>Failed to load</div>
  console.log(JSON.stringify(games))
  console.log('hiiii')
  console.log('heloo')
  if (isLoading) return <div>Loading...</div>
  
  return(disGames(games))
  

 
}
function disGames(aGames){

  const gamesArray = Object.values(aGames)

  return (
    <div className={styles.tablecontainer}>
    <table className={styles.myTable}>
        <thead>
          <tr>
            <th>Matchup</th>
            <th className={styles.myC}>{moment.tz('America/Los_Angeles').format('MMM DD, YYYY h:mm A')}</th>
          </tr>
        </thead>
        <tbody>
          {gamesArray.map((game) => (
            <tr key={game.id}>
              <td>{game.away_team} <br /> @ {game.home_team}</td>
              <td className={styles.myC}>{moment.utc(game.commence_time).tz('America/Los_Angeles').format('h:mm A')}</td>
              {disOdds(game)}
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

function disOdds(game) {
  const bookmakers = game.bookmakers;
  const columns = bookmakers.map((bookmaker) => {
    return (
      <td key={bookmaker.key}>
        <h2>{bookmaker.title}</h2>
        <table>
          <tbody>
            {bookmaker.markets.map((market) => (
              <React.Fragment key={market.key}>
                <tr>
                  <td colSpan="2"><h3>{market.key}</h3></td>
                </tr>
                {market.outcomes.map((outcome) => (
                  <tr key={outcome.name}>
                    <td>{outcome.name}</td>
                    <td>{outcome.price}</td>
                  </tr>
                ))}
              </React.Fragment>
            ))}
          </tbody>
        </table>
      </td>
    );
  });

  return <>{columns}</>;
}

export default function Home() {
  return (
    <>
      <Head>
        <title>Sports Betting App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        {Games()}

      </div>
    </>
  )

}
