# This is a basic workflow that is manually triggered

name: Manual workflow

on:
  schedule:
  - cron: "45 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run main method
      run: |
        python -c "main import nba_scores; nba_scores()"
